### ISSUE TITLE
[Feature Request] Add port commandline option

### ISSUE THREAD

**Issue by RincewindsHat** [MisterMountain/check_tftp#1]
Please add a commandline option for choosing the targeted port.
Yes, this will almost always not be in use, but if I want to test
a TFTP setup I can setup a server on a non-privileged port.

**Comment by MisterMountain** [comment]
As far as i know TFTP only supports running on Port 69

**Comment by RincewindsHat** [comment]
Are you sure about that? didn't see anything in RFC 1350, but I might be wrong.

**Comment by MisterMountain** [comment]
In the RFC 1350 i can only see it picks Port 69 for read and write requests:
>    Dest. Port      Picked by destination machine (69 for RRQ or WRQ).
According to other sites, its fixed to port 69. But i cant find anything clearly stating its 69 only

**Comment by RincewindsHat** [comment]
Indeed, still, for test setups and weird network quirks (relaying the port over machines and whatnot) it would still be nice to have and barely more effort.
But this is your decision

**Comment by MisterMountain** [comment]
As other ports seems not to be supported by the protocol there is no need for implementing this.
